### ISSUE TITLE
Write empty functions and docstrings

### ISSUE THREAD

**Issue by sreejithmunthikodu** [UBC-MDS/Kmeans_python#2]
As per our discussion in lab,
1. **Function to fit** - Implement k-means algorithm and get the centroids
2. **Function to predict** - given the centroids of the clusters, assign new data to the respective clusters. 
3. Function to select the best k using **silhotte method** - given a list of k and data, plot the silhouette score vs k
4. Function to select the best k using **elbow method** - given list of k and data, plot the inertia vs k
5. **Function to summarize the clusters** - Given a fitted k-means function, return the summary of clusters as a data frame- how many clusters, number of samples in each cluster, cluster quality, etc.

**Comment by sreejithmunthikodu** [comment]
Guys, let's discuss the possible functions, input arguments, and output here. Once we finalize the number and type of functions, we can open separate issues for each function and take ownership.

Also, we should discuss if we are using classes or independent functions.

**Comment by RobBlumberg** [comment]
I think elbow/silhouette can be included in the same function (a k-optimization function, say), with a parameter specifying the desired method. 

For fit, the input should be a dataframe or np.array with numerical features, and the output should be within-cluster mean squared errors, assigned clusters for training data and centroid locations?

**Comment by sreejithmunthikodu** [comment]
Sounds great. But if we are combining those two functions, we may have to think of more functionality/ additional functions to balance the work. Fit and optimizing k should be good enough. But I feel predict and summary functions may not be sufficient for two guys. What say?

**Comment by RobBlumberg** [comment]
Yes agreed, maybe we can create a function which fit can optionally call to better initialize the cluster centers (something analogous to kmeans++)

**Comment by sreejithmunthikodu** [comment]
That is a good idea. Let's do it.

Another option, I was thinking, anyways we have to use a scaler to normalize the data before clustering. So why not make a function for feature scaling? We can implement a MiniMaxScaler and a StandScaler in a single function.

**Comment by RobBlumberg** [comment]
The only thing with scaling the data is that we are then encroaching into data preprocessing, which usually is left to the data scientist to perform before using an ML algorithm. I'm not necessarily against it, but then it could lead us down a feature preprocessing rabbit hole, like for example, do we then also add imputation features to deal with potential missing data?

**Comment by sreejithmunthikodu** [comment]
I agree.... data preprocessing doesn't fit in the package. But I don't think it will damage the package. Could make it more robust. Maybe the user can specify if the data is already normalized. Let's see how much work we have .... if we feel the need for more functions we could include this.

**Comment by RobBlumberg** [comment]
Sounds good, you're right it would be a nice extra feature

**Comment by RobBlumberg** [comment]
One other important thing, I was thinking all our functions could be written inside a Kmeans class (atleast for python) so that we can have attributes for our kmeans objects, but this would mean that we would have 1 .py file with all the functions, and that would make it difficult to work on separate branches on our own functions. Not quite sure what the solution is here

**Comment by saurav193** [comment]
I think for now we can have separate functions in separate scripts. Later on we have to merge them into a single script in the package. Otherwise user have to mention the <package>.<script_name>.<function_name> to call a function which will be inconvenient. Also we need to create objects right, so there must be a class to define that. Can a script call function from other script? I'm not sure how to do that.

**Comment by RobBlumberg** [comment]
Yes it can, if you're in script A, you just need to do import "script B", and you get all the function from script B, kinda of like how we import pandas and get the pandas class and all its function.

But okay we can use different function for now, but when it comes to merging in a single class it will change the implementation slightly

**Comment by RobBlumberg** [comment]
We need to decide who will write the skeleton and docstring for each function. I'll just say I can do the summarizing / predict functions, Saurav take the fit function, Sree elbow method and James silhouette? This doesn't necessarily mean we'll be stuck with these functions for the whole project, its just to separate the work now, but if anyone wants to do a specific one thats fine. 

I think we should all agree on the inputs and outputs of each function in each function's relevant issue before merging anything.

Also, just to be consistent for each function, we should use the docstring format:

    """
    Description

    Parameters
    ----------
    a : type
      description
    b : type
      description

    Returns
    -------
    type
      description

    Examples
    --------
    >>> from foocat import foocat
    >>> a = pd.Categorical(["character", "hits", "your", "eyeballs"])
    >>> b = pd.Categorical(["but", "integer", "where it", "counts"])
    >>> foocat.catbind(a, b)
    [character, hits, your, eyeballs, but, integer, where it, counts]
    Categories (8, object): [but, character, counts,
    eyeballs, hits, integer, where it, your]
    """

**Comment by jamesh4** [comment]
Yeah I think sticking with that format is good. Since this milestone is just the empty shells and documentation this division is good. More importantly we need to create another repo for the R package, and have the python equivalent of everything. Most of the files will be duplicates, but the documentation should be in a different style. Tidyverse like in the R labs.

**Comment by sreejithmunthikodu** [comment]
| sl no | Function   | Input            | Output            | Misc           | 
|-------|------------|------------------|-------------------|----------------| 
| 1     | fit        | data             | centroids         |                | 
|       |            | n_clusters       | labels            |                | 
|       |            |                  | Inertia           |                | 
|       |            |                  |                   |                | 
| 2     | elbow      | data             | list of inertia   | generates plot | 
|       |            | list_k           |                   |                | 
|       |            |                  |                   |                | 
| 3     | silhouette | data             | list of sil_score | generates plot | 
|       |            | list_k           |                   |                | 
|       |            |                  |                   |                | 
| 4     | predict    | data             | labels            |                | 
|       |            | centroids        |                   |                | 
|       |            |                  |                   |                | 
| 5     | summarize  | data, n_clusters | inertia           | returns a df   | 
|       |            |                  | samples/cluster   |                | 
|       |            |                  | centroids         |                | 
|       |            |                  | ...               |                |

**Comment by sreejithmunthikodu** [comment]
Guys, a summary of the above discussion is attached above. I think we need to create separate issues for each function and assign who is responsible. I am ok with what Rob suggested. May be we could swap the roles between Python and R.

**Comment by sreejithmunthikodu** [comment]
Just noticed. @saurav193 already created these issues. Thanks

**Comment by RobBlumberg** [comment]
I also agree with swapping roles
