### ISSUE TITLE
Feedback of Milestone 1

### ISSUE THREAD

**Issue by Doooooris** [UBC-MDS/Kmeans_python#29]
- Functions in this package: Explain more detailed thing of what the function does, and what is input, etc (At least two sentences)
- Summary: Subjective tone, avoid using ‘we’. (Remember, this is package instructions for the user, not TA). 
- Messy branch and name. I found lots of branches, and I am not sure which one for which function. It looks messy and the name makes no sense to me. Please clean it, so it's easier to track.

**Comment by RobBlumberg** [comment]
Closing this issue as feedback has been added to relevant issue thread (See [here](https://github.com/UBC-MDS/Kmeans_python/issues/28))
