### ISSUE TITLE
implement fit function

### ISSUE THREAD

**Issue by saurav193** [UBC-MDS/Kmeans_python#41]

**Comment by sreejithmunthikodu** [comment]
Hi Saurav,
when I tested the function for larger values of k for iris dataset, it is throwing an error.

`from sklearn import datasets
iris = datasets.load_iris()
X = iris["data"]
fit(X, 20)`

The error is

`---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-3-acec9de09d49> in <module>
      2 iris = datasets.load_iris()
      3 X = iris["data"]
----> 4 fit(X, 20)

~/Documents/MDS_UBC/block_5/labs/COLAB_SW/Kmeans_python/Kmeans_python/fit.py in fit(X_train, k, n_init, max_iter)
    167         i = i + 1
    168 
--> 169     return centers_final, labels_final

UnboundLocalError: local variable 'centers_final' referenced before assignment`

It looks like for higher values of k, the `compute_distance(X, centers)` returns nans. So the below line is always false and breaks the code.
`if  updated_inertia < inertia:`  
Could you please have a look?
Thanks

**Comment by sreejithmunthikodu** [comment]
Here is how I managed to find a solution. Please have a look and confirm if this can be done. 

- The random initialization is initializing centers that are not in the samples. Hence, for larger k, there are some clusters which has zero samples. This results in nan
- I suggest replacing the randonm initialization function with the following code
`centers = X[np.random.choice(range(n_samples), k, replace=False), :]`
- This ensures that the random centers are chosen from the dataset itself.
- This now works for any k

**Comment by RobBlumberg** [comment]
I think this makes sense, since if a cluster centre is initialized far from the data, it will never be assigned points to begin with, and so will never move in future iterations
