### ISSUE TITLE
Feedback of Milestone 2

### ISSUE THREAD

**Issue by Doooooris** [UBC-MDS/Kmeans_python#55]
- The usage section is missing. Please write the usage section with the usage example of your functions. For example, Function 1: example input data .....; code to call the function 1 with input; example output data.

- Please document your test function, write comments inside the function to describe what are you test here.

- Run 'pytest tests/test_elbow.py' giving me error message 'from Kmeans_python.elbow import elbow; ModuleNotFoundError: No module named 'Kmeans_python'. Add an empty file named '__init__.py' solving the above issue.

- In Usage, add the example output too. (You can attach the image if the output is a graph).

- Function did not catch crazy input. For example, X = np.array([['B', 2], [1, 'A']]). Write assert for unexpected input.

- Lack of unit test. Please ensure you have tested the input, output, and algorithm for each function.

**Comment by sreejithmunthikodu** [comment]
- Usage added
- Add comments in test functions
- Added __init__.py 
- Added more edge cases
- Added unit tests
