### ISSUE TITLE
Feedback to milestone 3

### ISSUE THREAD

**Issue by Doooooris** [UBC-MDS/Kmeans_python#80]
1. In usage, silhouette.py. add 'from Kmeans_python.silhouette import silhouette'
2. Problem from last milestone: Function 'fit, elbow' did not catch crazy input. For example, X = np.array([['B', 2], [1, 'A']]). Write assert for unexpected input.
3. In usage, 'from Kmean_python.cluster_summary import cluster_summary' is incorrect. Kmeans_python not Kmean_python.
4. when i do 'cluster_summary(centers, cluster_ass)', an error shows up: TypeError: cluster_summary() missing 1 required positional argument: 'cluster_assignments'
5. When I try 'devtools::install_github("UBC-MDS/Kmeans")', error shows up: Error in library(tidyverse) : there is no package called ‘tidyverse’. Error: unable to load R code in package ‘Kmeans’. unable to install r.
6. code coverage should in CI too.
7. Adding more R unit test to get better code cov.
8. pip install python package failed. Try 'pip install -i https://test.pypi.org/simple/ 
Kmeans_python'. Looking in indexes: https://test.pypi.org/simple/
ERROR: Could not find a version that satisfies the requirement 
Kmeans_python (from versions: none) ERROR: No matching distribution found for 
Kmeans_python

**Comment by RobBlumberg** [comment]
We have addressed all the points above:

1. Added import line for silhouette in usage
2. Added defensive check for invalid inputs in fit and elbow methods
3. Fixed typo in import line in usage
4. Added missing argument to cluster_summary in usage
5. Added tidyverse as a dependency to fix this error.
6. Code coverge is now in CI
7. Added many unit tests to increase code coverage to 98%
8. Updated installation instructions to enable installing dependencies from PyPI, outside TestPyPi
