### ISSUE TITLE
 Function 'fit, elbow' did not catch crazy input. 

### ISSUE THREAD

**Issue by sreejithmunthikodu** [UBC-MDS/Kmeans_python#81]
- TA feedback
- For example, X = np.array([['B', 2], [1, 'A']]). Write assert for unexpected input.

**Comment by saurav193** [comment]
I'm updating the fit(). Can you change it to elbow() only

**Comment by sreejithmunthikodu** [comment]
May be we both can use the same issue?

**Comment by saurav193** [comment]
ok cool
